# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_aluno', '0002_auto_20170710_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bolsa_escola',
            field=models.NullBooleanField(default=False),
        ),
    ]
