# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161110_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situacao_aluno',
            old_name='data_conclusao',
            new_name='data_registro',
        ),
    ]
