# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170321_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='desempenho',
            name='periodo_curso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='numero_faltas',
            field=models.IntegerField(),
        ),
    ]
