# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161130_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='municipio',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
