# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161110_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='situacao_aluno',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Periodo'),
            preserve_default=False,
        ),
    ]
