# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matriz_curricular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('data_conclusao_ensino_medio', models.DateField()),
                ('codigo_social', models.CharField(max_length=255)),
                ('cor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Cor')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='departamentos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='campus',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Campus'),
        ),
        migrations.AlterField(
            model_name='matriz_curricular',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Sexo'),
        ),
    ]
