# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161201_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renda_Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
                ('codigo', models.IntegerField()),
            ],
        ),
    ]
