# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170321_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desempenho',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='numero_faltas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desempenho',
            name='percentual_presenca',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
