# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_renda_familiar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renda_familiar',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
