# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161103_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='departamentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campus'),
        ),
        migrations.AlterField(
            model_name='matriz_curricular',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
    ]
