# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tipo_escola_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_escola_origem',
            name='codigo',
            field=models.CharField(max_length=1),
        ),
    ]
