# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161103_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Situacao_Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='situacao',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='situacao_aluno',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno'),
        ),
        migrations.AddField(
            model_name='situacao_aluno',
            name='situacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Situacao'),
        ),
    ]
