# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_forma_ingresso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_conclusao_ensino_medio',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ano_conclusao_ensino_medio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ano_nascimento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
