# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161103_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='situacao_aluno',
            name='data_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
