# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161207_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='data_cadastro',
        ),
    ]
