# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161103_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='periodo_conclusao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='periodo_matricula',
        ),
        migrations.AlterField(
            model_name='situacao_aluno',
            name='data_registro',
            field=models.DateField(),
        ),
    ]
