# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_endereco_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='CEP',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
