# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161103_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matriz_curricular',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='matriz_curricular',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Matriz_Curricular',
        ),
    ]
