# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20161208_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forma_Ingresso_Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('forma_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Forma_Ingresso')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Renda_Familiar_Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa')),
                ('renda_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Renda_Familiar')),
            ],
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='CEP',
            new_name='cep',
        ),
        migrations.RemoveField(
            model_name='situacao_aluno',
            name='data_registro',
        ),
    ]
