# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161103_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cor',
            name='sigla',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sexo',
            name='sigla',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
