# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_escola_origem_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ano_reservistals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
