# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pessoa_ano_reservistals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='ano_reservistals',
            new_name='ano_reservista',
        ),
    ]
