# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20161104_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_conclusao_ensino_medio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
