# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161104_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
