# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField()),
                ('data_conclusao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('CEP', models.CharField(max_length=15)),
                ('data_cadastro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estrutura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Matriz_Curricular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estrutura')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField()),
                ('data_conclusao_ensino_medio', models.DateField()),
                ('codigo_social', models.CharField(max_length=255)),
                ('CEP', models.CharField(max_length=15)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cor')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco')),
                ('matriculas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sexo'),
        ),
        migrations.AddField(
            model_name='estado',
            name='municipios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipio'),
        ),
        migrations.AddField(
            model_name='curso',
            name='matrizes_curriculares',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Matriz_Curricular'),
        ),
        migrations.AddField(
            model_name='campus',
            name='departamentos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departamento'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matriz_curricular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Matriz_Curricular'),
        ),
    ]
