# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AP', 'APROVADO'), ('RN', 'REPROVADO_NOTA'), ('RF', 'REPROVADO_FALTA')], default='AP', max_length=2)),
                ('nota', models.IntegerField()),
                ('Disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='historico',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Periodo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='Historico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Historico'),
            preserve_default=False,
        ),
    ]
