# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161028_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estrutura',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
