# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161028_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='departamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Departamento'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='matrizes_curriculares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Matriz_Curricular'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cursos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Curso'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='Disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Disciplina'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Periodo'),
        ),
        migrations.AlterField(
            model_name='matriz_curricular',
            name='estrutura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Estrutura'),
        ),
        migrations.AlterField(
            model_name='matriz_curricular',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
