# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Cor',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Endereco',
            },
        ),
        migrations.CreateModel(
            name='Escola_Origem_Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Escola_Origem_Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Forma_Ingresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('sigla', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Forma_Ingresso',
            },
        ),
        migrations.CreateModel(
            name='Forma_Ingresso_Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('forma_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Forma_Ingresso')),
            ],
            options={
                'db_table': 'Forma_Ingresso_Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_nascimento', models.IntegerField(blank=True, null=True)),
                ('ano_conclusao_ensino_medio', models.IntegerField(blank=True, null=True)),
                ('ano_conclusao_primeiro_grau', models.IntegerField(blank=True, null=True)),
                ('codigo_social', models.CharField(max_length=255)),
                ('pai_falecido', models.BooleanField(default=False)),
                ('mae_falecido', models.BooleanField(default=False)),
                ('necessidade_fisica', models.BooleanField(default=False)),
                ('necessidade_auditiva', models.BooleanField(default=False)),
                ('necessidade_mental', models.BooleanField(default=False)),
                ('necessidade_multipla', models.BooleanField(default=False)),
                ('superdotado', models.BooleanField(default=False)),
                ('ano_reservista', models.IntegerField(blank=True, null=True)),
                ('bolsa_familia', models.BooleanField(default=False)),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Cor')),
            ],
            options={
                'db_table': 'Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Profissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Profissao',
            },
        ),
        migrations.CreateModel(
            name='Renda_Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'Renda_Familiar',
            },
        ),
        migrations.CreateModel(
            name='Renda_Familiar_Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Pessoa')),
                ('renda_familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Renda_Familiar')),
            ],
            options={
                'db_table': 'Renda_Familiar_Pessoa',
            },
        ),
        migrations.CreateModel(
            name='Reside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Reside',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Responsavel',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Sexo',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Escola_Origem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Tipo_Escola_Origem',
            },
        ),
        migrations.AddField(
            model_name='pessoa',
            name='profissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Profissao'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='reside',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Reside'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Sexo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Responsavel'),
        ),
        migrations.AddField(
            model_name='forma_ingresso_pessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Pessoa'),
        ),
        migrations.AddField(
            model_name='escola_origem_pessoa',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Pessoa'),
        ),
        migrations.AddField(
            model_name='escola_origem_pessoa',
            name='tipo_escola_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Tipo_Escola_Origem'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Pessoa'),
        ),
    ]
