# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-17 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoa', '0003_auto_20170710_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='bolsa_familia',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='codigo_social',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='mae_falecido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='necessidade_auditiva',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='necessidade_fisica',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='necessidade_mental',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='necessidade_multipla',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pai_falecido',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='superdotado',
            field=models.NullBooleanField(default=False),
        ),
    ]
