# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-17 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_pessoa', '0004_auto_20170817_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='profissao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_pessoa.Profissao'),
        ),
    ]
